language: python
python:
- 3.6
- 3.5
- 3.4
install: python setup.py install
script: python setup.py test
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: isabelleberger
  password:
    secure: nPpwxs01yKKn2akQ+7bV1p/F5ucYrPuu1kMDvpvinSNKB9CZ6s7KUQhBwPbNmXCCKCQBGmS1zjaqdqaYm68WWHT1sLajVfDiwWRLbzUs61AUIFY9RYO1x7qjz7sF4gL8jqmg8BKdKOFEww6jQhUaiEEmlspJoDGGAxZUIZL+7RV9LSLm0vYBsGKZYzYK1qyTjldUtP16zBG9FKYCteClv0UXTayi5Y0l8eVOoDzaBXuRWX5dZ7293pAUj9sCv4AzGVz55gtgeKj3/vHuEyQNZKJ9rjME6H8p4uh7mLq/HMUfoc0JqmdFg3zfV9+ReAPak/rbRo2yWWcL6KnMbUwA3AuW9n9yoMklIGUJ1iKaaSDm9hNex9UpvwWml8igmxV+OhmPvNo8nO/pN9gMFWI7EcnHIWeHT0hqXY58jremm1bIeLif94keePbkf27KwhStbPFIs920uo/NTbivS6TOqcsowhR3+wAcOX/DCrG9eMETZ1erjh/X4nZfrAepBS6EjpDCtFuZMnSZLN3Q2qvUpDctFtkGoEr2FzTnuJR0mAgxF831amI8jtFe3/DeQlNcXiasM17X4DxUoVw0KcUe3TGMkAmeFL9kPP3790DzAd5PC5c5Gp+0M+MK/d+QrZgEJAtCkXGvWV7G1YfXmLJqWxZPzAuG+aZ8COK7vEYCjEM=
  skip_cleanup: true
  on:
    tags: true
    repo: isabelleberger/drosSRA
    python: 3.6
